// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj116lXr5MDG7t-mMzeNJ47yPyW2lU0jM',
    appId: '1:738823612376:web:fe3c9e156a66fb8e5df4ad',
    messagingSenderId: '738823612376',
    projectId: 'fire-basic-a8627',
    authDomain: 'fire-basic-a8627.firebaseapp.com',
    storageBucket: 'fire-basic-a8627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZh15cE-uT9CKwhvMq5pP2-YUgkmHo_ik',
    appId: '1:738823612376:android:1e811f5c8498d21c5df4ad',
    messagingSenderId: '738823612376',
    projectId: 'fire-basic-a8627',
    storageBucket: 'fire-basic-a8627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07xs4yx50b1_rjN1CGrR_uRd3JiiDa8k',
    appId: '1:738823612376:ios:a155fb6c1ef835eb5df4ad',
    messagingSenderId: '738823612376',
    projectId: 'fire-basic-a8627',
    storageBucket: 'fire-basic-a8627.appspot.com',
    iosClientId:
        '738823612376-nr17ve5ntaspv4al0jg7ts6d5c38u0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasebasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD07xs4yx50b1_rjN1CGrR_uRd3JiiDa8k',
    appId: '1:738823612376:ios:a155fb6c1ef835eb5df4ad',
    messagingSenderId: '738823612376',
    projectId: 'fire-basic-a8627',
    storageBucket: 'fire-basic-a8627.appspot.com',
    iosClientId:
        '738823612376-nr17ve5ntaspv4al0jg7ts6d5c38u0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasebasic',
  );
}
